### ISSUE TITLE
Script creates thousands of folders

### ISSUE THREAD

**Issue by vince-p** [spraot/gphotos-sync#11]
I have the script working and it is downloading photos. But it seems to be downloading each within its own subfolder.
For example in the log I have entries such as:
  `level=infoworkerId=5itemId=AF1QipO9MNhbeG39gEeJhsdLlOhz4uYJKP8Bs2ulhwCjbatchItemIndex=5isOriginal=falsedt=2025-03-26T21:43:54.063Zmessage=downloaded file(s) PXL_20210322_033938256.jpg with date 2021-03-22`

This is actually downloading a file into a folder called AF1QipO9MNhbeG39gEeJhsdLlOhz4uYJKP8Bs2ulhwCj
So in my output folder I end up with
\AF1QipO9MNhbeG39gEeJhsdLlOhz4uYJKP8Bs2ulhwCj\PXL_20210322_033938256.jpg

Am I doing something wrong?
Please advice how to get these downloaded files organised properly.

Here is my docker config:

```
services:
  gphotos-sync:
    build:
      context: https://github.com/spraot/gphotos-sync.git#cd9244a2d83d5ca3b273e24e320fa53dea8d4b5a
      # I recommend using a specific commit instead though:
      # context: https://github.com/spraot/gphotos-sync.git#{FULL_GIT_HASH}
      # Optionally override the version of gphotos-cdp to use (requires rebuilding the docker image):
      # args:
      #   - GPHOTOS_CDP_VERSION=github.com/spraot/gphotos-cdp@COMMITISH
    container_name: gphotos-sync
    restart: unless-stopped
    privileged: true # chrome seems to need this to run as 1000:1000
    volumes:
      - /scratch/docker_data/gphotos-sync/profile:/tmp/gphotos-cdp # this is the correct profile folder for my setup
      - /pool/Photos/gphotos:/download
    environment:
      - PUID=1000  # Set to the current user's uid
      - PGID=1000  # Set to the current user's gid
      - CRON_SCHEDULE=41 * * * *
      - RESTART_SCHEDULE=26 1 * * 0
      #- HEALTHCHECK_ID=d6e4a333-ce52-4129-9d3e-6722c3333333
      - LOGLEVEL=info
      - TZ=Australia/Sydney
      #- ALBUMS=  # comma separated list of album IDs to sync
      #- GPHOTOS_CDP_ARGS=  # additional arguments to pass to gphotos-cdp
```
