### ISSUE TITLE
The program often crashes with various errors and requires a lot of manual intervention

### ISSUE THREAD

**Issue by dabajabaza** [spraot/gphotos-sync#13]
@spraot thank you for this great program!

I've checked the existing issues and couldn’t find anything similar, so it seems I might be the only one encountering these errors. Am I doing something wrong?

Here is my docker-compose.yml:
```
services:
  gphotos-sync:
    build:
      context: https://github.com/spraot/gphotos-sync.git
    container_name: gphotos-sync
    restart: unless-stopped
    privileged: true
    volumes:
      - ./profile:/tmp/gphotos-cdp
      - ./gphotos:/download
    environment:
      - PUID=1001
      - PGID=1001
      - CRON_SCHEDULE=25 * * * *
      - RESTART_SCHEDULE=26 1 * * 0
      - HEALTHCHECK_ID=d6e4a333-ce52-4129-9d3e-6722c3333333
      - LOGLEVEL=info
      - TZ=Asia/Bangkok
      - ALBUMS=ALL
      - GPHOTOS_CDP_ARGS=-json=false
```
Here are the errors I'm seeing during photo sync.
Each time one of these occurs, I have to manually restart the container:
```
12:00:19 FTL failure during sync: encountered error 'json: Unmarshal(nil *bool)' when requesting download
12:18:12 FTL failure during sync: while checking if video is still processing context deadline exceeded
11:29:56 FTL failure during sync: error navigating to item AF1QipOcEZitgw0QGhYlRMunVSlmC__hpVLwwczcou-r: navigate aborted: context deadline exceeded
```
Is there a way to automatically restart the container when such errors occur?
