### ISSUE TITLE
Only works in English?

### ISSUE THREAD

**Issue by bmaster001** [spraot/gphotos-sync#2]
I tried your (very promising!) tool, but it fails because my Google Photos is in Dutch ...

This is the error I get:
{"level":"fatal","dt":"2025-02-03T18:56:35.617Z","message":"selector \"[aria-label=\\\"Open info\\\"]\" did not return any nodes"}

Which seems to be a correct error, because when I look at the page source for Google Photos I see this:

aria-label="Info openen"

Probably this kind of errors will occur at some other places as well :(

**Comment by spraot** [comment]
I did attempt to fix the locale in gphotos-cdp, so either that didn’t work,
or this project isn’t pointing at the latest version of gphotos-cdp. You
can set the version if necessary with a build-arg as shown in the readme,
but unfortunately I wont have an opportunity to look at this for the next
couple weeks. Sorry!

**Comment by bmaster001** [comment]
No worries :-)
As far as I know, the most gphotos-cdp is in use, so I think it doesn't really work. When you have time again, I'm happy to help test this!

For now, I tried setting the language to English (country Belgium) in the google account. Didn't make any difference at first, but after either waiting a few hours, or starting with a new chrome profile (not sure which one helped), I now get this:

:"parsing time \"19 Nov 2008 Wed, 16:29 +0100\" as \"Jan 2, 2006 Mon, 3:04PM Z0700\": cannot parse \"19 Nov 2008 Wed, 16:29 +0100\" as \"Jan\""}

So something did change! When I have some more time, I'll try setting the country to US and recreate the chrome profile again. Maybe that fixes it too.

**Comment by spraot** [comment]
Sounds good! I don't think it's feasible to make this version of gphotos-cdp work on an arbitrary locale. Google makes their HTML very difficult to parse, so the UI text is the only way we can recognize elements. I don't see any region settings on my account, but language is set to "English (United States)", and that may be the only setting that works.

**Comment by bmaster001** [comment]
It's working fine as it is, so maybe best to not break it :-)

**Comment by spraot** [comment]
I documented it in the readme and linked to this issue, let's leave it at that.

**Comment by bmaster001** [comment]
Maybe better to continue https://github.com/spraot/gphotos-sync/issues/8#issuecomment-2692923926 here?

**Comment by bmaster001** [comment]
I just took a quick look. When I open a photo, there are about 60 aria-label attributes when I search for in in the page source. I hope you don't need them all? :-)  Do you know an easy way to collect these things? And what exactly do you need, because just the contents could not be enough since I think you don't understand Dutch and can't match them to the English version?

**Comment by spraot** [comment]
Fill out as many of these as possible with the Dutch equivalents:

```
en:
  selectAllPhotosLabel:
    matchType: startsWith
    matchValue: "Select all photos from"
  fileNameLabel:
    matchType: startsWith
    matchValue: "Filename:"
  dateLabel:
    matchType: startsWith
    matchValue: "Date taken:"
  today: "Today"
  yesterday: "Yesterday"
  timeLabel:
    matchType: startsWith
    matchValue: "Time taken:"
  tzLabel:
    matchType: startsWith
    matchValue: "GMT"
  viewPreviousPhotoMatch:
    matchType: equals
    matchValue: "View previous photo"
  moreOptionsLabel:
    matchType: equals
    matchValue: "More options"
  downloadLabel:
    matchType: equals
    matchValue: "Download - Shift+D"
  downloadOriginalLabel:
    matchType: equals
    matchValue: "Download original"
  openInfoMatch:
    matchType: equals
    matchValue: "Open info"
  videoStillProcessingDialogLabel:
    matchType: startsWith
    matchValue: "Video still is processing"
  videoStillProcessingStatusText: "Video is still processing &amp; can be downloaded later"
  noWebpageFoundText: "No webpage was found for the web address:"
  shortDayNames: 
    - "Sun"
    - "Mon"
    - "Tue"
    - "Wed"
    - "Thu"
    - "Fri"
    - "Sat"
```

**Comment by bmaster001** [comment]
I'll fill this in further when I get more time:
```
nl:
  selectAllPhotosLabel:
    matchType: startsWith
    matchValue: "Alle foto's van" -->  complete sentence is like: "Alle foto's van Vandaag selecteren"
  fileNameLabel:
    matchType: startsWith
    matchValue: "Bestandsnaam:"
  dateLabel:
    matchType: startsWith
    matchValue: "Fotodatum:"
  today: "Vandaag"
  yesterday: "Gisteren"
  timeLabel:
    matchType: startsWith
    matchValue: "Tijdsduur:" --> which is actually a wrong translation :-)
  tzLabel:
    matchType: startsWith
    matchValue: "GMT" --> Same ("GMT+01:00")
  viewPreviousPhotoMatch:
    matchType: equals
    matchValue: ""Vorige foto bekijken"    
  moreOptionsLabel:
    matchType: equals
    matchValue: "Meer opties"
  downloadLabel:
    matchType: equals
    matchValue: "Download - Shift+D"
  downloadOriginalLabel:
    matchType: equals
    matchValue: "Download original" -->  I don't see this yet
  openInfoMatch:
    matchType: equals
    matchValue: "Info openen"
  videoStillProcessingDialogLabel:
    matchType: startsWith
    matchValue: "Video still is processing"
  videoStillProcessingStatusText: "Video is still processing &amp; can be downloaded later"
  noWebpageFoundText: "No webpage was found for the web address:"
  shortDayNames: 
    - "Sun"
    - "Mon"
    - "Tue"
    - "Wed"
    - "Thu"
    - "Fri"
    - "Sat"
```

**Comment by spraot** [comment]
You will also need to update gphotos-sync to 4cb5be6965c9b89f7a9881e48a6efe74df0e1513 btw.

**Comment by bmaster001** [comment]
> Good start. To test it, save that file somewhere, upgrade to gphotos-cdp@7c085d92 then add this to your docker compose
Will try that later today, thanks for the updates!
Does the first line matter? it was 'en:' and I changed it to 'nl:'?

**Comment by spraot** [comment]
Yeah, nl looks like it's right for Dutch.

**Comment by bmaster001** [comment]
Here's the output of testsync.sh with loglevel=trace:

```
{"level":"info","dt":"2025-03-03T19:01:25.323Z","message":"Successfully authenticated"}
{"level":"debug","dt":"2025-03-03T19:01:25.339Z","message":"Loaded locale nl with values\n{{startsWith Alle foto's van} {startsWith Bestandsnaam:} {startsWith Fotodatum:} Vandaag Gisteren {startsWith Tijdsduur:} {startsWith GMT} {equals Vorige foto bekijken} {equals Meer opties} {equals Download - Shift+D} {equals Download original} {equals Info openen} {startsWith Video still is processing} Video is still processing &amp; can be downloaded later No webpage was found for the web address: [Zo Ma Di Wo Do Vr Za]}"}
{"level":"info","dt":"2025-03-03T19:01:25.339Z","message":"Loaded locales: nl"}
{"level":"info","dt":"2025-03-03T19:01:25.339Z","message":"Using locale nl"}
{"level":"trace","dt":"2025-03-03T19:01:25.339Z","message":"Attempting to find first item"}
{"level":"debug","dt":"2025-03-03T19:01:25.884Z","message":"Page loaded, most recent item in the feed is: AF1QipMx03jLe09IQb-O-ysHfR4J6yYKvDq0v3Htyigr"}
{"level":"debug","dt":"2025-03-03T19:01:28.377Z","message":"Finding end of page"}
{"level":"debug","dt":"2025-03-03T19:01:40.311Z","message":"Successfully jumped to the end"}
{"level":"info","dt":"2025-03-03T19:01:41.368Z","message":"Nav to the end sequence is started because location is https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q"}
{"level":"debug","dt":"2025-03-03T19:01:42.478Z","message":"Location: https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q"}
{"level":"trace","dt":"2025-03-03T19:01:42.48Z","message":"processing AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q"}
{"level":"trace","dt":"2025-03-03T19:01:42.48Z","message":"entering downloadAndProcessItem() for https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q"}
{"level":"trace","dt":"2025-03-03T19:01:42.48Z","message":"Getting photo data for https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q"}
{"level":"debug","dt":"2025-03-03T19:01:42.48Z","message":"Extracting photo date text and original file name"}
{"level":"trace","dt":"2025-03-03T19:01:42.481Z","message":"entering startDownload() for https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q, dlOriginal=false"}
{"level":"debug","original":"false","dt":"2025-03-03T19:01:42.481Z","message":"Requesting download (method 2) for https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q"}
{"level":"trace","dt":"2025-03-03T19:01:42.499Z","message":"Parsing date: 3 jul 2016 and time: zo, 15:37"}
{"level":"trace","dt":"2025-03-03T19:01:42.499Z","message":"Parsing filename: IMG_20160703_153718797.jpg"}
{"level":"error","location":"https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q","dt":"2025-03-03T19:01:43.519Z","message":"waiting for 'download' button failed due to context deadline exceeded when requesting download with method 2, trying again"}
{"level":"error","location":"https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q","dt":"2025-03-03T19:01:44.629Z","message":"waiting for 'download' button failed due to context deadline exceeded when requesting download with method 2, trying again"}
{"level":"error","location":"https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q","dt":"2025-03-03T19:01:45.735Z","message":"waiting for 'download' button failed due to context deadline exceeded when requesting download with method 2, trying again"}
{"level":"error","location":"https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q","dt":"2025-03-03T19:01:46.841Z","message":"waiting for 'download' button failed due to context deadline exceeded when requesting download with method 2, trying again"}
{"level":"error","location":"https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q","dt":"2025-03-03T19:01:47.945Z","message":"waiting for 'download' button failed due to context deadline exceeded when requesting download with method 2, trying again"}
{"level":"error","location":"https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q","dt":"2025-03-03T19:01:49.051Z","message":"waiting for 'download' button failed due to context deadline exceeded when requesting download with method 2, trying again"}
{"level":"debug","location":"https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q","dt":"2025-03-03T19:01:50.155Z","message":"trying to request download with method 2 6 times, giving up now"}
{"level":"debug","dt":"2025-03-03T19:01:50.155Z","message":"Checking download status of https://photos.google.com/photo/AF1QipPoCnbaOCvp5KYuamofE4nPPWsVpmheB_dDOe2Q"}
{"level":"trace","dt":"2025-03-03T19:01:50.155Z","message":"Checking for still processing dialog"}
{"level":"trace","dt":"2025-03-03T19:01:50.156Z","message":"Checking for still processing status (at bottom of screen)"}
{"level":"trace","dt":"2025-03-03T19:01:50.16Z","message":"Checking for loading error page"}
{"level":"trace","dt":"2025-03-03T19:01:50.188Z","message":"Checking for still processing dialog"}
{"level":"trace","dt":"2025-03-03T19:01:50.189Z","message":"Checking for still processing status (at bottom of screen)"}
{"level":"trace","dt":"2025-03-03T19:01:50.192Z","message":"Checking for loading error page"}
{"level":"trace","dt":"2025-03-03T19:01:50.221Z","message":"Checking for still processing dialog"}
{"level":"trace","dt":"2025-03-03T19:01:50.222Z","message":"Checking for still processing status (at bottom of screen)"}

```
These last lines continue for a long time, so I aborted.

**Comment by bmaster001** [comment]
Oh wait that was in legacy mode. I removed that and now I get this:

```
{"level":"info","dt":"2025-03-03T19:04:46.48Z","message":"photo AF1QipMx03jLe09IQb-O-ysHfR4J6yYKvDq0v3Htyigr (Video - Staand - 1 mrt 2025, 20:55:21) is missing. Downloading it."}
{"level":"info","dt":"2025-03-03T19:04:46.481Z","message":"1 download jobs currently in progress"}
{"level":"trace","dt":"2025-03-03T19:04:46.481Z","message":"Navigating to https://photos.google.com/photo/AF1QipMx03jLe09IQb-O-ysHfR4J6yYKvDq0v3Htyigr"}
{"level":"info","dt":"2025-03-03T19:04:46.552Z","message":"photo AF1QipOJLTAeBiw4W_ptvIhf-Trn8Lw_WJo_MRS7jAC8 (Video - Staand - 1 mrt 2025, 20:50:20) is missing. Downloading it."}
{"level":"trace","dt":"2025-03-03T19:04:46.552Z","message":"Navigating to https://photos.google.com/photo/AF1QipOJLTAeBiw4W_ptvIhf-Trn8Lw_WJo_MRS7jAC8"}
{"level":"info","dt":"2025-03-03T19:04:46.61Z","message":"photo AF1QipPgZLWo-gSOzmZcbFgck5HVVYtsJpcnGtxZBQWp (Video - Staand - 1 mrt 2025, 20:48:07) is missing. Downloading it."}
{"level":"trace","dt":"2025-03-03T19:04:46.612Z","message":"Navigating to https://photos.google.com/photo/AF1QipPgZLWo-gSOzmZcbFgck5HVVYtsJpcnGtxZBQWp"}
{"level":"info","dt":"2025-03-03T19:04:46.667Z","message":"photo AF1QipNl0jIlCGdwoU-_spf_lJ7F2P5xJK5kYeoUMCme (Foto - Staand - 1 mrt 2025, 20:47:26) is missing. Downloading it."}
{"level":"trace","dt":"2025-03-03T19:04:46.667Z","message":"Navigating to https://photos.google.com/photo/AF1QipNl0jIlCGdwoU-_spf_lJ7F2P5xJK5kYeoUMCme"}
{"level":"info","dt":"2025-03-03T19:04:46.729Z","message":"photo AF1QipMv23tACtOqiVvGcb7ruviN0gj3c5VBpgLnXSCU (Foto - Staand - 1 mrt 2025, 20:43:33) is missing. Downloading it."}
{"level":"trace","dt":"2025-03-03T19:04:46.73Z","message":"Navigating to https://photos.google.com/photo/AF1QipMv23tACtOqiVvGcb7ruviN0gj3c5VBpgLnXSCU"}
{"level":"info","dt":"2025-03-03T19:04:47.227Z","message":"photo AF1QipOBZyUQnw7GP8p0mSa615T-IoSHHKzU5reHv_ob (Foto - Liggend - 1 mrt 2025, 19:22:26) is missing. Downloading it."}
{"level":"trace","dt":"2025-03-03T19:04:47.228Z","message":"Navigating to https://photos.google.com/photo/AF1QipOBZyUQnw7GP8p0mSa615T-IoSHHKzU5reHv_ob"}
{"level":"trace","dt":"2025-03-03T19:04:52.671Z","message":"entering downloadAndProcessItem() for https://photos.google.com/photo/AF1QipNl0jIlCGdwoU-_spf_lJ7F2P5xJK5kYeoUMCme"}
{"level":"trace","dt":"2025-03-03T19:04:52.671Z","message":"Getting photo data for https://photos.google.com/photo/AF1QipNl0jIlCGdwoU-_spf_lJ7F2P5xJK5kYeoUMCme"}
{"level":"debug","dt":"2025-03-03T19:04:52.672Z","message":"Extracting photo date text and original file name"}
{"level":"trace","dt":"2025-03-03T19:04:52.671Z","message":"entering startDownload() for https://photos.google.com/photo/AF1QipNl0jIlCGdwoU-_spf_lJ7F2P5xJK5kYeoUMCme, dlOriginal=false"}
{"level":"debug","original":"false","dt":"2025-03-03T19:04:52.672Z","message":"Requesting download (method 2) for https://photos.google.com/photo/AF1QipNl0jIlCGdwoU-_spf_lJ7F2P5xJK5kYeoUMCme"}
{"level":"trace","dt":"2025-03-03T19:04:53.03Z","message":"entering downloadAndProcessItem() for https://photos.google.com/photo/AF1QipOJLTAeBiw4W_ptvIhf-Trn8Lw_WJo_MRS7jAC8"}
{"level":"trace","dt":"2025-03-03T19:04:53.03Z","message":"Getting photo data for https://photos.google.com/photo/AF1QipOJLTAeBiw4W_ptvIhf-Trn8Lw_WJo_MRS7jAC8"}
{"level":"debug","dt":"2025-03-03T19:04:53.031Z","message":"Extracting photo date text and original file name"}
{"level":"trace","dt":"2025-03-03T19:04:53.031Z","message":"entering startDownload() for https://photos.google.com/photo/AF1QipOJLTAeBiw4W_ptvIhf-Trn8Lw_WJo_MRS7jAC8, dlOriginal=false"}
{"level":"trace","dt":"2025-03-03T19:04:53.435Z","message":"Incomplete data - Date: , Time: , Timezone: , File name: "}
{"level":"debug","dt":"2025-03-03T19:04:53.435Z","message":"Date not visible, clicking on i button"}
{"level":"trace","dt":"2025-03-03T19:04:53.625Z","message":"entering downloadAndProcessItem() for https://photos.google.com/photo/AF1QipMv23tACtOqiVvGcb7ruviN0gj3c5VBpgLnXSCU"}
{"level":"trace","dt":"2025-03-03T19:04:53.625Z","message":"Getting photo data for https://photos.google.com/photo/AF1QipMv23tACtOqiVvGcb7ruviN0gj3c5VBpgLnXSCU"}
{"level":"debug","dt":"2025-03-03T19:04:53.625Z","message":"Extracting photo date text and original file name"}
{"level":"trace","dt":"2025-03-03T19:04:53.625Z","message":"entering startDownload() for https://photos.google.com/photo/AF1QipMv23tACtOqiVvGcb7ruviN0gj3c5VBpgLnXSCU, dlOriginal=false"}
{"level":"trace","dt":"2025-03-03T19:04:54.317Z","message":"Incomplete data - Date: , Time: , Timezone: GMT+01:00, File name: "}
{"level":"debug","dt":"2025-03-03T19:04:54.317Z","message":"Date not visible, clicking on i button"}
{"level":"trace","dt":"2025-03-03T19:04:54.394Z","message":"entering downloadAndProcessItem() for https://photos.google.com/photo/AF1QipOBZyUQnw7GP8p0mSa615T-IoSHHKzU5reHv_ob"}
{"level":"trace","dt":"2025-03-03T19:04:54.394Z","message":"Getting photo data for https://photos.google.com/photo/AF1QipOBZyUQnw7GP8p0mSa615T-IoSHHKzU5reHv_ob"}
{"level":"debug","dt":"2025-03-03T19:04:54.394Z","message":"Extracting photo date text and original file name"}
{"level":"trace","dt":"2025-03-03T19:04:54.394Z","message":"entering startDownload() for https://photos.google.com/photo/AF1QipOBZyUQnw7GP8p0mSa615T-IoSHHKzU5reHv_ob, dlOriginal=false"}
{"level":"trace","dt":"2025-03-03T19:04:54.843Z","message":"entering downloadAndProcessItem() for https://photos.google.com/photo/AF1QipMx03jLe09IQb-O-ysHfR4J6yYKvDq0v3Htyigr"}
{"level":"trace","dt":"2025-03-03T19:04:54.843Z","message":"Getting photo data for https://photos.google.com/photo/AF1QipMx03jLe09IQb-O-ysHfR4J6yYKvDq0v3Htyigr"}
{"level":"debug","dt":"2025-03-03T19:04:54.843Z","message":"Extracting photo date text and original file name"}
{"level":"trace","dt":"2025-03-03T19:04:54.843Z","message":"entering startDownload() for https://photos.google.com/photo/AF1QipMx03jLe09IQb-O-ysHfR4J6yYKvDq0v3Htyigr, dlOriginal=false"}
{"level":"trace","dt":"2025-03-03T19:04:54.923Z","message":"entering downloadAndProcessItem() for https://photos.google.com/photo/AF1QipPgZLWo-gSOzmZcbFgck5HVVYtsJpcnGtxZBQWp"}
{"level":"trace","dt":"2025-03-03T19:04:54.923Z","message":"Getting photo data for https://photos.google.com/photo/AF1QipPgZLWo-gSOzmZcbFgck5HVVYtsJpcnGtxZBQWp"}
{"level":"debug","dt":"2025-03-03T19:04:54.923Z","message":"Extracting photo date text and original file name"}
{"level":"trace","dt":"2025-03-03T19:04:54.923Z","message":"entering startDownload() for https://photos.google.com/photo/AF1QipPgZLWo-gSOzmZcbFgck5HVVYtsJpcnGtxZBQWp, dlOriginal=false"}
{"level":"error","location":"https://photos.google.com/photo/AF1QipNl0jIlCGdwoU-_spf_lJ7F2P5xJK5kYeoUMCme","dt":"2025-03-03T19:04:56.64Z","message":"waiting for 'download' button failed due to context deadline exceeded when requesting download with method 2, trying again"}
{"level":"trace","dt":"2025-03-03T19:04:56.669Z","message":"Incomplete data - Date: , Time: , Timezone: , File name: "}
{"level":"debug","dt":"2025-03-03T19:04:56.669Z","message":"Date not visible, clicking on i button"}
{"level":"trace","dt":"2025-03-03T19:04:57.405Z","message":"Incomplete data - Date: , Time: , Timezone: , File name: "}
{"level":"debug","dt":"2025-03-03T19:04:57.405Z","message":"Date not visible, clicking on i button"}
{"level":"trace","dt":"2025-03-03T19:04:58.112Z","message":"Parsing date: 1 mrt and time: za, 19:22"}
{"level":"trace","dt":"2025-03-03T19:04:58.112Z","message":"Parsing filename: PXL_20250301_182226577.MP.jpg"}
{"level":"trace","dt":"2025-03-03T19:04:58.136Z","message":"Incomplete data - Date: , Time: , Timezone: , File name: "}
{"level":"debug","dt":"2025-03-03T19:04:58.136Z","message":"Date not visible, clicking on i button"}
{"level":"fatal","dt":"2025-03-03T19:04:58.172Z","message":"failed to parse \"1 mrt, za, 19:22 GMT+01:00\": unknown format"}
```

**Comment by spraot** [comment]
It's not able to find the download button (probably no label is matching your locale) and it's not able to parse the date. You won't be able to resolve the date part, so I'll have a look at that.

**Comment by bmaster001** [comment]
Thanks. Meanwhile I found the typo in the download label...

**Comment by spraot** [comment]
Locale wasn't actually set for date parsing, but that's fixed in cdp@298dc859

**Comment by bmaster001** [comment]
It works!
`{"level":"debug","dt":"2025-03-03T19:24:49.332Z","message":"Found date: {nl Day 2025-03-01 09:41:00 +0100 UTC+01:00} and original filename: PXL_20250301_084132018.jpg"}`

**Comment by bmaster001** [comment]
Not everything is translated yet, because I don't know how to find these labels:

"Download original"
"Video still is processing"
"Video is still processing &amp; can be downloaded later"
"No webpage was found for the web address:"

**Comment by spraot** [comment]
If you edit a photo in google photos, it will keep the original and show that button so that you can download it. The others were probably only relevant for me because I've somehow accumulated every possible edge case in my library :)

**Comment by spraot** [comment]
You may need to update gphotos-cdp first, but I think you can sync both accounts with one instance with something like this:

ALBUMS=u/0,u/1

**Comment by bmaster001** [comment]
> If you edit a photo in google photos, it will keep the original and show that button so that you can download it. The others were probably only relevant for me because I've somehow accumulated every possible edge case in my library :)

I'll play with that when the initial sync is complete! It halted last night but after restarting it this morning, it's still running now... 


> You may need to update gphotos-cdp first, but I think you can sync both accounts with one instance with something like this:
> ALBUMS=u/0,u/1

It's probably me, but how does that work? What is u/0 and u/1 and how can I make it download to another folder?

**Comment by spraot** [comment]
If you log into multiple accounts in one browser, you'll notice that URLs differentiate between accounts by adding u/0, u/1, etc.I think we can treat those sort of like albums in order to sync them in a single gphotos-sync container.

I don't have a setup where I can test that right now, but I think setting ALBUMS=u/0 will download that users library to DL_DIR/0

**Comment by bmaster001** [comment]
I didn't try the multi-account yet, but I updated to the most recent versions of sync and cdp, and now the sync for the Dutch account fails. I get lots of "unhandled page event *page.EventFrameStartedNavigating" and then a runtime error:

```
2025/03/09 19:34:13 ERROR: unhandled page event *page.EventFrameStartedNavigating
2025/03/09 19:34:14 ERROR: unhandled page event *page.EventFrameStartedNavigating
2025/03/09 19:34:14 ERROR: unhandled page event *page.EventFrameStartedNavigating
{"level":"debug","GUID":"aad82a3f-7bd6-4932-bc04-c0d274cf0345","dt":"2025-03-09T19:34:15.262+01:00","message":"Download of PXL_20250308_195614629.mp4 started"}
panic: runtime error: index out of range [8] with length 7

goroutine 53 [running]:
main.(*Session).getPhotoData(0xc0023d7400?, {0xc67ac0, 0xc00235aeb0})
        /go/pkg/mod/github.com/spraot/gphotos-cdp@v0.0.0-20250304232153-db74e8906261/main.go:947 +0x865
main.(*Session).downloadAndProcessItem.func1()
        /go/pkg/mod/github.com/spraot/gphotos-cdp@v0.0.0-20250304232153-db74e8906261/main.go:1205 +0x108
created by main.(*Session).downloadAndProcessItem in goroutine 37
        /go/pkg/mod/github.com/spraot/gphotos-cdp@v0.0.0-20250304232153-db74e8906261/main.go:1203 +0x1bf

```

**Comment by spraot** [comment]
I've been hitting the same error. There was a bug in handling of photos from yesterday (in the localisation code). This is fixed now. 

I also lost authentication on my laptop test profile, but not on my server. I don't think it's related.

**Comment by bmaster001** [comment]
Thanks. The fix worked for the Dutch account.
The English one needed re-authentication, but now fails again with something new:

```
{"level":"debug","dt":"2025-03-10T07:59:46.766+01:00","message":"Setting file date for [/download/AF1QipMI-2q_CZeqxceecjwBAapIjYd9qDyMcw5EOniP/PXL_20250309_161650197.MP.jpg]"}
{"level":"debug","dt":"2025-03-10T07:59:46.766+01:00","message":"Running /app/postdl.sh on /download/AF1QipMI-2q_CZeqxceecjwBAapIjYd9qDyMcw5EOniP/PXL_20250309_161650197.MP.jpg"}
2025/03/10 07:59:47 ERROR: unhandled page event *page.EventFrameStartedNavigating
    1 files failed condition
{"level":"fatal","dt":"2025-03-10T07:59:47.679+01:00","message":"exit status 2"}

```

**Comment by spraot** [comment]
Everything seems to be working again

**Comment by bmaster001** [comment]
Looking very good indeed! Thanks for the quick fixes (again)!
Do you need anything elkse from me regarding the Dutch translation?

**Comment by spraot** [comment]
Please share your locale.yaml with me and I'll add it to the library's locales list. I'm also curious what the dates look like in dutch. The date parser I'm using seems kind of flaky, so I'm considering changing it, but I haven't seen anything else that supports different locales out of the box.

**Comment by bmaster001** [comment]
Does this help you with the dates?

![Image](https://github.com/user-attachments/assets/96454648-ff07-4db6-9501-cddc9e21305c)


> If you edit a photo in google photos, it will keep the original and show that button so that you can download it. The others were probably only relevant for me because I've somehow accumulated every possible edge case in my library :)

I tried this, but I just get 2 photos, both with a normal 'download' button, not a 'download original' button. 

Attaching a yaml file is not allowed, but here are the contents of my locale.yaml file:

```
nl:
  selectAllPhotosLabel:
    matchType: startsWith
    matchValue: "Alle foto's van"
  fileNameLabel:
    matchType: startsWith
    matchValue: "Bestandsnaam:"
  dateLabel:
    matchType: startsWith
    matchValue: "Fotodatum:"
  today: "Vandaag"
  yesterday: "Gisteren"
  timeLabel:
    matchType: startsWith
    matchValue: "Tijdsduur:"
  tzLabel:
    matchType: startsWith
    matchValue: "GMT"
  viewPreviousPhotoMatch:
    matchType: equals
    matchValue: "Vorige foto bekijken"
  moreOptionsLabel:
    matchType: equals
    matchValue: "Meer opties"
  downloadLabel:
    matchType: equals
    matchValue: "Downloaden - Shift+D"
  downloadOriginalLabel:
    matchType: equals
    matchValue: "Download original"
  openInfoMatch:
    matchType: equals
    matchValue: "Info openen"
  videoStillProcessingDialogLabel:
    matchType: startsWith
    matchValue: "Video still is processing"
  videoStillProcessingStatusText: "Video is still processing &amp; can be downloaded later"
  noWebpageFoundText: "No webpage was found for the web address:"
  shortDayNames:
    - "Zo"
    - "Ma"
    - "Di"
    - "Wo"
    - "Do"
    - "Vr"
    - "Za"
```

**Comment by spraot** [comment]
Thanks, that's part of the lib now :)

**Comment by spraot** [comment]
The date parsing lib I used was failing randomly, so I've implemented simple date parsing directly in this project. If you upgrade you'll need a few more values in your locale.yaml, or you can just stop using that file since it should be build in now.

```
nl:
  selectAllPhotosLabel:
    matchType: startsWith
    matchValue: "Alle foto's van"
  fileNameLabel:
    matchType: startsWith
    matchValue: "Bestandsnaam:"
  dateLabel:
    matchType: startsWith
    matchValue: "Fotodatum:"
  today: "Vandaag"
  yesterday: "Gisteren"
  timeLabel:
    matchType: startsWith
    matchValue: "Tijdsduur:"
  tzLabel:
    matchType: startsWith
    matchValue: "GMT"
  viewPreviousPhotoMatch:
    matchType: equals
    matchValue: "Vorige foto bekijken"
  moreOptionsLabel:
    matchType: equals
    matchValue: "Meer opties"
  downloadLabel:
    matchType: equals
    matchValue: "Downloaden - Shift+D"
  downloadOriginalLabel:
    matchType: equals
    matchValue: "Download original"
  openInfoMatch:
    matchType: equals
    matchValue: "Info openen"
  videoStillProcessingDialogLabel:
    matchType: startsWith
    matchValue: "Video still is processing"
  videoStillProcessingStatusText: "Video is still processing &amp; can be downloaded later"
  noWebpageFoundText: "No webpage was found for the web address:"
  shortDayNames:
    - "zo"
    - "ma"
    - "di"
    - "wo"
    - "do"
    - "vr"
    - "za"
  longDayNames:
    - "zondag"
    - "maandag"
    - "dinsdag"
    - "woensdag"
    - "donderdag"
    - "vrijdag"
    - "zaterdag"
  shortMonthNames:
    - "jan"
    - "feb"
    - "mrt"
    - "apr"
    - "mei"
    - "jun"
    - "jul"
    - "aug"
    - "sep"
    - "okt"
    - "nov"
    - "dec"
```
